//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Units
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Units()
        {
            this.Equipment = new HashSet<Equipment>();
            this.Weapons = new HashSet<Weapons>();
        }
    
        public int Unit_ID { get; set; }
        public string Unit_Number { get; set; }
        public Nullable<int> Location_ID { get; set; }
        public Nullable<int> Branch_ID { get; set; }
        public Nullable<int> Company_Count { get; set; }
        public Nullable<int> Equipment_Count { get; set; }
        public Nullable<int> Weapon_Count { get; set; }
        public string UnitPhoto { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Equipment> Equipment { get; set; }
        public virtual Location Location { get; set; }
        public virtual Military_Branch Military_Branch { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Weapons> Weapons { get; set; }
    }
}
