//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Weapons
    {
        public int Weapon_ID { get; set; }
        public string Weapon_Name { get; set; }
        public Nullable<int> Unit_ID { get; set; }
        public string Specifications { get; set; }
    
        public virtual Units Units { get; set; }
    }
}
